{
 "title": "SPARK_DASH_Linux",
 "tags": [
  "linux",
  "process_exporter",
  "node_exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node_instance",
    "label": "Node_exporter",
    "query": {
     "query": "label_values(up{job=\"node_exporter\"},instance)"
    }
   },
   {
    "name": "Process_instance",
    "label": "Process_exporter",
    "query": {
     "query": "label_values(up{job=\"process_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Partition usage, disk reading, disk writing, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest usage rate collected.\n\nNumber of connections: CurrEstab - Number of TCP connections with current status ESTABLISHED or CLOSE-WAIT.\n\nThe health value is a new indicator. A value calculated based on CPU, memory, and IO, which is less than 90 points, indicates that the system's resource usage needs to be paid attention to. This is an indicator being tested, and the parameters may need to be optimized according to the actual situation.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"node_exporter\"} - 0",
     "legendFormat": "Host Name"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\"} - 0",
     "legendFormat": "Total memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node_exporter\",mode='system'}) by (instance)",
     "legendFormat": "Total number of audits"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"node_exporter\"} / (node_memory_MemTotal_bytes{job=\"node_exporter\"})))* 100",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"node_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{\nfstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"node_exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"node_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"node_exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=\"node_exporter\"}[5m])) by (instance)",
     "legendFormat": "Maximum read"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=\"node_exporter\"}[5m])) by (instance)",
     "legendFormat": "Maximum write"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"node_exporter\"} - 0",
     "legendFormat": "Number of connections"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"node_exporter\"} - 0",
     "legendFormat": "TCPwait_time"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=\"node_exporter\"}[5m])*8) by (instance)",
     "legendFormat": "Download bandwidth"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=\"node_exporter\"}[5m])*8) by (instance)",
     "legendFormat": "Upload bandwidth"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$Node_instance\",job=\"node_exporter\"} - node_boot_time_seconds{instance=~\"$Node_instance\",job=\"node_exporter\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Total CPU usage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "IOwait usage rate"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} / (node_memory_MemTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",})))* 100",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{\nfstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~\"$Node_instance\",job=\"node_exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partition Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Average CPU usage percentage across all cores over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Total connection",
   "type": "timeseries",
   "description": "Current number of established TCP connections on the node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$Node_instance\",job=\"node_exporter\",}",
     "legendFormat": "TCP Connections"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Percentage of memory currently used on the node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",} / (node_memory_MemTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\",})))* 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Shows the total physical memory (RAM) available.\n\nUsed memory on the node excluding memory used for caches, buffers, and reclaimable slab memory — effectively the memory actively used by processes",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Swap Memory Used",
   "type": "timeseries",
   "description": "Displays the total amount of swap memory available on the node.\nDisplays the total amount of swap memory used on the node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"} - node_memory_SwapFree_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "Swap Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Disk Space Used ",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs\"}) \n - sum(node_filesystem_avail_bytes{device!~\"rootfs\"})\n",
     "legendFormat": "Disk space Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs\"})",
     "legendFormat": "Total Disk Space"
    }
   ]
  },
  {
   "title": "Disk Read Write",
   "type": "timeseries",
   "description": "current rate of disk reads and write in bytes per second (B/s)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Time to read and write each IO (reference: less than 100ms)",
   "type": "timeseries",
   "description": "Read time seconds The number of seconds the read operation takes per disk partition\n\nWrite time seconds The number of seconds the write operation per disk partition is taken",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])",
     "legendFormat": "{{device}}_Write"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])",
     "legendFormat": "{{device}}_weighted"
    }
   ]
  },
  {
   "title": "Use $device per second network bandwidth",
   "type": "timeseries",
   "description": "Shows the incoming network bandwidth in bits per second (bps) over the last 5 minutes.\nIt calculates how much data the node is receiving across all interfaces.\n\nShows the outgoing network bandwidth in bits per second (bps) over the last 5 minutes.\nIt reflects how much data the node is sending out.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])*8",
     "legendFormat": "{{device}}_inDownload"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$Node_instance\",job=\"node_exporter\"}[5m])*8",
     "legendFormat": "{{device}}_out Upload"
    }
   ]
  },
  {
   "title": "System average load",
   "type": "timeseries",
   "description": "Shows the 1-minute load average — the average number of runnable processes over the last minute.\n\nDisplays the 5-minute load average — smoother than 1-minute, good for short-term trends.\n\nShows the 15-minute load average — best for viewing long-term CPU load trends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "1 minute load"
    },
    {
     "expr": "node_load5{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "5 minutes load"
    },
    {
     "expr": "node_load15{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "15 minutes load"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "timeseries",
   "description": "Shows the total number of sockets (TCP, UDP, etc.) currently in use on the selected node.\nThis gives an overview of how many network connections or endpoints are actively being used by the system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "Sockets_used - Sockets currently in use"
    }
   ]
  },
  {
   "title": "Sockstat TCP",
   "type": "timeseries",
   "description": "Shows the number of TCP sockets allocated.\n\nDisplays the number of TCP sockets currently in use.\n\nShows the amount of memory (in pages) used by TCP sockets.\n\nDisplays the number of TCP sockets in TIME_WAIT state — meaning the connection was closed but is still waiting to ensure the remote side received the final ACK.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "TCP_alloc - Allocated sockets"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "TCP_inuse - Tcp sockets currently in use"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "TCP_mem - Used memory for tcp"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "TCP_tw - Sockets waiting close"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "timeseries",
   "description": "Shows the number of UDPLite sockets currently in use.\n\nShows the number of active UDP sockets currently in use.\n\nShows the amount of memory (in pages) used by all UDP sockets.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "UDP_inuse - Udp sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=~\"$Node_instance\",job=\"node_exporter\"}",
     "legendFormat": "UDP_mem - Used memory for udp"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Processes Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "time() - (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$Process_instance\", job=\"process_exporter\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Processes",
   "type": "piechart",
   "description": "Number of processes in the group.",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,namedprocess_namegroup_num_procs{instance=~\"$Process_instance\", job=\"process_exporter\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "description": "Actual memory usage by the process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,namedprocess_namegroup_memory_bytes{instance=~\"$Process_instance\", job=\"process_exporter\", memtype=\"resident\"}\n/\nignoring(memtype)\nnamedprocess_namegroup_num_procs{instance=~\"$Process_instance\", job=\"process_exporter\"}\n> 0)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "%CPU by services",
   "type": "timeseries",
   "description": " CPU usage as a percentage of total CPU cores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[1m])) by (groupname)\n> 0)\n/\nscalar(\n  count(\n    count(node_cpu_seconds_total{instance=~\"$Node_instance\", job=\"node_exporter\"}) by (cpu)\n  )\n)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU (millicore)",
   "type": "timeseries",
   "description": "Calculates the per-second CPU usage per process group.\nThe metric is a counter that represents the total CPU time consumed by a process group in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,(sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[$__rate_interval])) by (groupname) > 0) * 1000)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Number Threads",
   "type": "timeseries",
   "description": "Current number of threads used by each process group.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,namedprocess_namegroup_num_threads{instance=~\"$Process_instance\", job=\"process_exporter\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Total File Descriptors",
   "type": "timeseries",
   "description": "USED - Number of currently open file descriptors by the process.\nMAX-The maximum number of file descriptors the process is allowed to open (soft limit).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$Process_instance\", job=\"process_exporter\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "process_max_fds{instance=~\"$Process_instance\", job=\"process_exporter\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "description": "The number of bytes written by the group.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": " Read Bytes",
   "type": "timeseries",
   "description": "A cumulative counter for the number of bytes read by each process group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_read_bytes_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Major Page Faults",
   "type": "timeseries",
   "description": "Cumulative counter of major page faults per process group.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_major_page_faults_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Minor Page Faults",
   "type": "timeseries",
   "description": "A minor page fault happens when a process accesses a memory page that is not in its working set but is already in RAM — so it doesn't require disk access.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_minor_page_faults_total{instance=~\"$Process_instance\", job=\"process_exporter\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}